library point.im;

// This code was generated by the QIP OTA Wizard  
// You can find all SDK information at http://wiki.qip.ru/SDK_Map 

uses
  u_plugin_info,
  MainUnit in 'MainUnit.pas';

{$R icon.res}

{***********************************************************}
function CreateInfiumPLUGIN(PluginService: IQIPPluginService): IQIPPlugin; stdcall;
begin
  Result := TQipPlugin.Create(PluginService);
end;

exports
  CreateInfiumPLUGIN name 'CreateInfiumPLUGIN';

end.